### ISSUE TITLE
Build ERROE

### ISSUE THREAD

**Issue by yiwenzhang666999** [tumic0/QtPBFImagePlugin#11]
When I build the project in the windows environment, the following error appears. I don’t know if I downloaded the wrong Zlib or used the wrong problem. The website where I downloaded zlib is http://www.winimage.com/zLibDll
![image](https://user-images.githubusercontent.com/31643589/116178624-7b1e4f80-a748-11eb-952b-7b4c0087b14a.png)
![image](https://user-images.githubusercontent.com/31643589/116179406-ddc41b00-a749-11eb-9423-1b1fb1c100b8.png)

**Comment by tumic0** [comment]
First of all, I wouldn't mix libraries build with mingw with libraries build with MSVC, it will probably not work. But your actual problem is most probably something different - your zlib path is quiet weird... Have a look at the documentation and check your qmake parameters.
