### ISSUE TITLE
Teaming up with Vector Tiles Reader plugin for QGIS?

### ISSUE THREAD

**Issue by sfkeller** [tumic0/QtPBFImagePlugin#2]
Very interesting application! You should definitely have a look at our Vector Tiles Reader plugin for QGIS
https://github.com/geometalab/Vector-Tiles-Reader-QGIS-Plugin/ . I think there are some nice opportunities to exchange ideas. /cc @mnboos

**Comment by tumic0** [comment]
I'm not sure if there is a significant overlap between the two projects. From what I read about the QGIS plugin you do transform the vector tiles to some other data & style representation. QtPBFImagePlugin on the other hand is much more about the rendering of the data.

**Comment by sfkeller** [comment]
No problem with this and regarding raster MBTiles maps you're right. 

Regarding display of PBF vector tiles there are IMO still some commonalities with our QGIS VT Reader plugin like reading metadata, data decoding and e.g. dealing with sprites, icons and fonts. 

I'd also like to encourage you to report back your usage experiences with vector tiles to @flippmoke, the maintainer of https://github.com/mapbox/vector-tile-spec . Citing your README: "Due to a major design flaw in the Mapbox vector tiles specification - the zoom is not part of the PBF data - the plugin can not be used "as is", but passing the zoom level is necessary."

**Comment by flippmoke** [comment]
@sfkeller I can report that in VT3 we are adding an tile Zoom, X, Y as optional data https://github.com/mapbox/vector-tile-spec/blob/v3.0-development/3.0/vector_tile.proto#L138-L140

Hopefully this will make things a bit easier, but it isn't a required field currently for VT3.

**Comment by tumic0** [comment]
What about reconsidering the optionality of the zoom. Without the zoom, you can not display the tile data without providing external info, which is definitely a huge design flaw. With the zoom being part of the data, you can create an image plugin, that makes all existing software (Qt in this case, but most probably other frameworks have a similar plugins concept) display the vector tiles like it it can display raster images. So every map viewer could display vector maps or even every image viewer could display PBF files like it displays PNG or JPEG files. After all, it is only a single byte per tile.
