### ISSUE TITLE
Some layers are not rendered

### ISSUE THREAD

**Issue by sikmir** [tumic0/QtPBFImagePlugin#3]
I try to use [Klokantech Terrain](https://raw.githubusercontent.com/openmaptiles/klokantech-terrain-gl-style/master/style.json) style with GPXSee and here is the result:
![scr2](https://user-images.githubusercontent.com/688044/49860695-60630e80-fe0b-11e8-9173-2f3a2256e526.jpg)
And compare with [openmaptiles.github.io/klokantech-terrain-gl-style](https://openmaptiles.github.io/klokantech-terrain-gl-style/#12.5/69.3171/21.2742):
![scr1](https://user-images.githubusercontent.com/688044/49860836-a4eeaa00-fe0b-11e8-873d-2c89be65b415.png)
All layers that use `hillshading` or `contours` sources are not rendered.
[style.json](https://github.com/openmaptiles/klokantech-terrain-gl-style/blob/014d553f2d7358c921a897590e43b04cfe4745eb/style.json#L19-L33):
```json
  "sources": {
    "openmaptiles": {
      "type": "vector",
      "url": "https://free.tilehosting.com/data/v3.json?key={key}"
    },
    "hillshading": {
      "type": "raster",
      "url": "https://klokantech.tilehosting.com/data/hillshades.json?key=tXme5cuqgrCqdPoZHqyn",
      "tileSize": 256
    },
    "contours": {
      "type": "vector",
      "url": "https://klokantech.tilehosting.com/data/contours.json?key=tXme5cuqgrCqdPoZHqyn"
    }
},
```
I guess there is some known QtPBFImagePlugin limitation.

**Comment by tumic0** [comment]
The plugin renders only layers that are part of the PBF data. The hillshading and contours layers would have to be downloaded. This is not only something that I would not like an image plugin to do, but it is even impossible as the plugin does not know the x/y coordinates of the tile.

But it is a good point, that this is missing in the documentation.
