### ISSUE TITLE
Q: Is it really necessary to pass the zoom level?

### ISSUE THREAD

**Issue by sikmir** [tumic0/QtPBFImagePlugin#4]
README says:

> Due to a major design flaw in the Mapbox vector tiles specification - the zoom is not part of the PBF data - the plugin can not be used "as is", but passing the zoom level is necessary.

But I've tried to use .pbf tiles within other applications (not GPXSee) without any modifications (for passing the zoom level) and everything works as expected. I've also tried to build GPXSee without passing the zoom level to QImageReader and it works as well. Do I miss something?

**Comment by tumic0** [comment]
Without the zoom, all the zoom based style features do not work (properly). So you see something even without passing the zoom, but it is not how it should be rendered (road lines are too thick/thin etc.).

**Comment by sikmir** [comment]
Oh, I see now. Thanks. I've just used a dark style, where such details are not so noticeable.
