### ISSUE TITLE
 memory leak?

### ISSUE THREAD

**Issue by rusproger** [tumic0/QtPBFImagePlugin#9]
I use this code to convert vector tiles to png image:

[9-12-453.zip](https://github.com/tumic0/QtPBFImagePlugin/files/4857349/9-12-453.zip)
[9-12-453.zip](https://github.com/tumic0/QtPBFImagePlugin/files/4857350/9-12-453.zip)
`   QImage *_image = new QImage();

foreach (QString filename, listFiles)
{
    QImageReader _reader(filename, QString("0").toLatin1());

    _reader.setScaledSize(QSize(256, 256));
    if (_reader.read(_image))
    {
        _image->save(filename+".png","PNG");

    }
}
    delete _image;`

the memory occupied by the application is growing...

**Comment by tumic0** [comment]
I can not reproduce any leak using a +/- same code/data. So either there is something wrong in your Qt version (or some library that Qt uses) or the problem is somewhere else in your code. Provide the full code (+the real data) you are using if you want me to look deeper into the issue.

**Comment by tumic0** [comment]
You can try the code after fd02b83b47954a7d31dfdf7c7831b696ce095a85. Theoretically this should not change anything, but one never knows in C++...

**Comment by rusproger** [comment]
[PBF.zip](https://github.com/tumic0/QtPBFImagePlugin/files/4860233/PBF.zip)
Qt5.4.1+visual studio 2010

protobuf-cpp-3.2.0, 

 zlib-1.2.11

**Comment by rusproger** [comment]
> You can try the code after fd02b83. Theoretically this should not change anything, but one never knows in C++...

same result

**Comment by tumic0** [comment]
At the first sight, there is nothing suspicious, except the wrong constant zoom level you use (but that has nothing to do with a memory leak). Try to compile/run the [pbf2png](https://github.com/tumic0/pbf2png) example tool and see if it also leaks with your Qt/compiler setup (You may replace the QtConcurrent parallelisation with a simple sequential loop to get closer to your use case).

If it leaks, than there is some problem in your setup. If not, than the problem is in your code.

**Comment by rusproger** [comment]
Memory leak observed for some tiles. The program  pbf2png prints a message "QRegularExpressionPrivate::doMatch(): called on an invalid QRegularExpression object"

The only thing fixed in the source code of QtPBFImagePlugin: in Qt 5.4.1, the QFont :: Weight enumeration does not contain
Thin, ExtraLight, Medium, ExtraBold value

**Comment by tumic0** [comment]
> The program pbf2png prints a message "QRegularExpressionPrivate::doMatch(): called on an invalid QRegularExpression object"

With the default `([0-9]+).*` regexp? Works fine for me...

I would generally recommend you to use some newer Qt version - 5.4 is quiet archaic and most probably contains some already fixed  bugs causing the memory leak (and the broken regex)
